dist: xenial
language: ruby
sudo: false

cache:
  bundler: true
  directories:
    - /home/travis/.rvm/gems

rvm:
  - 2.5
  - 2.6

env:
  matrix:
    - RAILS_VERSION=v6.0.0 GEM=activerecord:mysql2
    - RAILS_VERSION=v6.0.0 GEM=activerecord:sqlite3
    - RAILS_VERSION=v6.0.0 GEM=activerecord:postgresql
    - RAILS_VERSION=v6.0.1.rc1 GEM=activerecord:mysql2
    - RAILS_VERSION=v6.0.1.rc1 GEM=activerecord:sqlite3
    - RAILS_VERSION=v6.0.1.rc1 GEM=activerecord:postgresql
    - RAILS_VERSION=v6.0.2.rc2 GEM=activerecord:mysql2
    - RAILS_VERSION=v6.0.2.rc2 GEM=activerecord:sqlite3
    - RAILS_VERSION=v6.0.2.rc2 GEM=activerecord:postgresql

services:
  - mysql
addons:
  postgresql: "10"

before_install:
  - unset BUNDLE_GEMFILE
  - gem update --system
  - gem update bundler

install:
  - git clone https://github.com/rails/rails.git ~/build/rails
  - pushd ~/build/rails
  - git checkout $RAILS_VERSION
  - sed -i "s/Gem.ruby, '-w'/Gem.ruby, '-w0'/" ~/build/rails/activerecord/Rakefile
  - sed -i "s/t.warning = true/t.warning = false/g" ~/build/rails/activerecord/Rakefile
  - sed -i "/require 'support\/connection'/a \$LOAD_PATH.unshift\(File.expand_path\('~\/build\/malomalo\/arel-extensions\/lib'\)\)\nrequire 'arel/extensions'" ~/build/rails/activerecord/test/cases/helper.rb
  - "sed -i \"/group :db do/a gem 'arel-extensions', require: 'arel/extensions', path: File.expand_path\\('~\\/build\\/malomalo\\/arel-extensions'\\)\" ~/build/rails/Gemfile"
  - sed -i "/rb-inotify/d" ~/build/rails/Gemfile
  - cat ~/build/rails/Gemfile
  - bundle install --jobs=3 --retry=3
  - popd

script:
  - cd ~/build/rails && ci/travis.rb
